# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b4b4a851dda6d20e1babfeea1f9e2eb3"
name = "PlayKu"
handle = "playku"
application_url = "https://di-livecam-clearance-boss.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_metaobject_definitions, write_metaobject_definitions, read_metaobjects, write_metaobjects, read_script_tags, write_script_tags, read_files, write_files"

[auth]
redirect_urls = [
  "https://di-livecam-clearance-boss.trycloudflare.com/auth/callback",
  "https://di-livecam-clearance-boss.trycloudflare.com/auth/shopify/callback",
  "https://di-livecam-clearance-boss.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://di-livecam-clearance-boss.trycloudflare.com/app-proxy/playku"
subpath = "playku"
prefix = "apps"

[pos]
embedded = false
